# Generated by Django 4.2.13 on 2024-07-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Changeset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeset_id', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('open', models.BooleanField(null=True)),
                ('changes_count', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('min_lat', models.FloatField(null=True)),
                ('max_lat', models.FloatField(null=True)),
                ('min_lon', models.FloatField(null=True)),
                ('max_lon', models.FloatField(null=True)),
                ('comments_count', models.IntegerField(null=True)),
                ('tags', models.JSONField(null=True)),
            ],
        ),
    ]
