# Generated by Django 4.2.13 on 2024-08-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='history',
            field=models.JSONField(default=list, null=True),
        ),
    ]
