# Generated by Django 4.2.13 on 2024-08-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0002_changeset_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='sequence_from',
            field=models.IntegerField(null=True),
        ),
    ]
