# Generated by Django 4.2.13 on 2024-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0003_changeset_sequence_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changeset',
            old_name='tags',
            new_name='additional_tags',
        ),
        migrations.AddField(
            model_name='changeset',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='hashtags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='locale',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
