# Generated by Django 4.2.13 on 2024-08-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0004_rename_tags_changeset_additional_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='hashtags',
            field=models.JSONField(default=list, null=True),
        ),
    ]
