# Generated by Django 4.2.13 on 2024-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0005_alter_changeset_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='imagery_used',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
