# Generated by Django 6.0.6 on 2026-07-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0006_changeset_host_changeset_imagery_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['created_at'], name='changesets__created_b0417c_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['closed_at'], name='changesets__closed__73f10a_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['user'], name='changesets__user_00df47_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['created_by'], name='changesets__created_c85966_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['changes_count'], name='changesets__changes_7e77d6_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['sequence_from'], name='changesets__sequenc_2cc4af_idx'),
        ),
    ]
