# Generated by Django 6.0.6 on 2026-07-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0007_alter_changeset_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='ml_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='suspicion_flags',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='changeset',
            name='suspicion_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['suspicion_score'], name='changesets__suspici_38ed8b_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['ml_score'], name='changesets__ml_scor_2c5ce6_idx'),
        ),
    ]
