# Generated by Django 6.0.6 on 2026-07-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changesets', '0008_changeset_ml_score_changeset_suspicion_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='country_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['country_code'], name='changesets__country_daad6f_idx'),
        ),
    ]
